# -*- coding: utf-8 -*-
# Generated by Django 1.9.9 on 2018-03-08 07:55
from __future__ import unicode_literals

from django.db import migrations, models
import menu.models


class Migration(migrations.Migration):

    dependencies = [
        ('menu', '0003_auto_20180307_2335'),
    ]

    operations = [
        migrations.AlterField(
            model_name='menu',
            name='expiration_date',
            field=models.DateTimeField(default=menu.models.thirty_day),
        ),
    ]
